# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  OUTPUT_DIR = "jenkins_build"

  desc "Android Project Clean"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Android-test 测试包"
  lane :fat do |options|
    parentOutputDir = OUTPUT_DIR
    versionCode=options[:code]
    puts versionCode
    # outputDir = parentOutputDir + "/fat/" + versionCode
    # puts outputDir
    gradle(
      task: "assemble",
      build_type:"Release",
      print_command: true,
      properties: {
          "versionCode" => versionCode
      }
    )
  end

  desc "Android-release 发布包"
  lane :pro do |options|
    parentOutputDir = OUTPUT_DIR
    versionCode=options[:code]
    puts versionCode
    # outputDir = parentOutputDir + "/fat/" + versionCode
    # puts outputDir
    gradle(
      task: "assemble",
      build_type:"Release",
      print_command: true,
      properties: {
          "versionCode" => versionCode,
          "dtJksPropertyPath" => "../../../../../../../certs/hellosud/hellosud_jks_release.properties"
      }
    )
  end
end
